### ISSUE TITLE
PyEVALIDator Updates

### ISSUE THREAD

**Issue by wzip** [New-Jersey-Forest-Service/FIAPI#35]
The PyEVALIDator updates that we discussed in "State of the Project" on 09/12/2018 have been pushed to Development along with a testing implementation (FIATestRun08.py) to test these changes and an example of a working URL to query a JSON file from the EVALIDator URL (workingURL.txt).  The new version of PYEVALIDator is still returning errors either related to the requests library or an issue with the url string being constructed.  Please follow up with testing.

**Comment by timbo112711** [comment]
The new version, `1.6`,  is now working and has been pushed to the Development branch. The problem was both in the way the URL and the denominator variable was constructed. In the older versions, when having no denominator you passed the string `'No denominator - just produce estimate.'` With the updated docs the string is now `'No denominator - just produce estimates'`. Also, the `other` variable did not have the correct `ptime, rtime` and ` ctime` strings. The last two were missing and `ptime` had no equal sign in it. After fixing this, the queries ran and returned a json blob. There are a few other changes that can be seen in the latest commit. 

This new version has been tested slightly with a few different variables and conditions. More rigorous testing should be performed. I will test it and Bill said he was going to test it as well. Will answer any questions next meeting, 9/26.

**Comment by wzip** [comment]
So, far this has passed my initial tests.  Excellent work!  I think we should discuss putting it though the rigors a bit at the next "State of the Project" and a timeline for merging development with main.

**Comment by timbo112711** [comment]
Awesome, thanks! I agree, we should test it at least one more week so that we can find anything that may be hidden in there that will through an error. I think we are very close to being ready for merging with master.

**Comment by wzip** [comment]
I am closing this issue since version 2.0 of PyEVALIDator in development was merged with Master.  Thanks, Tim for your hard work on this!
